### ISSUE TITLE
Could you provide the test_gt_segments.py file?

### ISSUE THREAD

**Issue by zfhxi** [naraysa/D2-Net#4]
Hello, when I run the release code, I met the following error:
```
Iteration: 500, Loss: 0.059, LDis: 0.059, LDS: 0.000, LDV: 0.000
Testing test data point 0 of 212
Testing test data point 100 of 212
Testing test data point 200 of 212
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    acc = test(itr, dataset, args, model, logger, device)
  File "/home/xxxx/Projects/_Reproduce/D2-Net-main/test.py", line 58, in test
    dmap, iou = dmAP(tcam_stack, dataset.path_to_annotations, args.activity_net, valid_id=dataset.lst_valid)
  File "/home/xxxx/Projects/_Reproduce/D2-Net-main/detectionMAP.py", line 324, in getDetectionMAP
    detections, gtsegments, temporal_labels, duration = getDetections(predictions, annotation_path, activity_net, valid_id)
  File "/home/xxxx/Projects/_Reproduce/D2-Net-main/detectionMAP.py", line 89, in getDetections
    gtseg = np.load('Thumos14reduced-Annotations/test_gt_segments.npy',allow_pickle=True)
  File "/home/xxxx/anaconda3/envs/co2/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Thumos14reduced-Annotations/test_gt_segments.npy'
```
Could you help me?

**Comment by naraysa** [comment]
Have added the annotations folder.
